Convert

diff --git a/.github/workflows/custom-board-update-rusefi-reference.yaml b/.github/workflows/custom-board-update-rusefi-reference.yaml
--- a/.github/workflows/custom-board-update-rusefi-reference.yaml
+++ b/.github/workflows/custom-board-update-rusefi-reference.yaml
@@ -16,15 +16,15 @@ jobs:
 
       - name: Git Checkout Submodules
         run: |
-          git submodule update --init --depth=1 ext/rusefi
+          git submodule update --init --depth=1 ext/gerefi
 
       - name: Dump GitHub context
         env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
         run: echo "$GITHUB_CONTEXT"
 
-      - name: Fetch remote lts-* branches of rusefi submodule
-        working-directory: ext/rusefi
+      - name: Fetch remote lts-* branches of gerefi submodule
+        working-directory: ext/gerefi
         run: |
           git fetch --depth=1 origin '+refs/heads/lts-*:refs/remotes/origin/lts-*'
           git branch -r
@@ -33,14 +33,14 @@ jobs:
         run: |
           git submodule update --remote
 
-      - name: Commit fresh 'ext/rusefi' submodule
+      - name: Commit fresh 'ext/gerefi' submodule
         env:
           ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub git update Action"
-          git add ext/rusefi
-          OUT=$(git commit -am "GHA says update ext/rusefi submodule" 2>&1) || echo "commit failed, finding out why"
+          git add ext/gerefi
+          OUT=$(git commit -am "GHA says update ext/gerefi submodule" 2>&1) || echo "commit failed, finding out why"
           if echo "$OUT" | grep 'nothing to commit'; then
             echo "submodule: looks like nothing to commit"
             echo "NOCOMMIT=true" >> $GITHUB_ENV
